### ISSUE TITLE
CSS-Klasse doppelt bei mehrzeiligen Spalten

### ISSUE THREAD

**Issue by weipah** [4t2/simple_columns#18]
Hi, 
ich weiß leider nicht, ob die Extension noch gepflegt wird, aber ich versuche trotzdem mal mein Glück.

Wenn man eine Spalte mit mehreren Elementen einrichtet und ein Umschlagselement haben möchte, dann erhalten beide Divs die CSS-Klasse, die man mit gibt:
![image](https://cloud.githubusercontent.com/assets/1555658/13808973/eb6f245e-eb68-11e5-9993-ffab1eb60eb2.png)

![image](https://cloud.githubusercontent.com/assets/1555658/13808977/f0621b2e-eb68-11e5-878e-73658b498a4d.png)

**Comment by Babelfisch** [comment]
Ja, das ist Absicht. Du kannst dann mit:
```css
.sc.productbox { /* kein Leerzeichen */ }

.sc .productbox { /* mit Leerzeichen */ }
```
jeweils das äußere Element oder die inneren Elemente gestalten.

**Comment by weipah** [comment]
@Babelfisch ah, OK so habe ich jetzt quasi auch meinen "Workaround" gestaltet.

Danke für die prompte Antwort!
